repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    # When updating, also check if tflint version in pre-commit workflow can be updated.
    rev: "v0.1.23" # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-validate # It should be the first step as it runs terraform init required by tflint
      - id: terraform-fmt
      - id: tflint

# TODO: Check if those hooks would be better.
# - repo: https://github.com/antonbabenko/pre-commit-terraform
#   rev: v1.88.0
#   hooks:
#     - id: terraform_fmt
#     - id: terraform_validate
#     - id: terraform_docs
#       args:
#         - '--args=--lockfile=false'
#     - id: terraform_tflint
#       args:
#         - '--args=--only=terraform_deprecated_interpolation'
#         - '--args=--only=terraform_deprecated_index'
#         - '--args=--only=terraform_unused_declarations'
#         - '--args=--only=terraform_comment_syntax'
#         - '--args=--only=terraform_documented_outputs'
#         - '--args=--only=terraform_documented_variables'
#         - '--args=--only=terraform_typed_variables'
#         - '--args=--only=terraform_module_pinned_source'
#         - '--args=--only=terraform_naming_convention'
#         - '--args=--only=terraform_required_version'
#         - '--args=--only=terraform_required_providers'
#         - '--args=--only=terraform_standard_module_structure'
#         - '--args=--only=terraform_workspace_remote'

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0" # Get the latest from: https://github.com/terraform-docs/terraform-docs/releases
    hooks:
      - id: terraform-docs-go
        args: ["."]

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "2.5.13" # Get the latest from: https://github.com/bridgecrewio/checkov/releases
    hooks:
      - id: checkov
        args: [--skip-check, "CKV_TF_1"] # Terraform module sources do not use a git url with a commit hash revision

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0" # Get the latest from: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-yaml
